POST http://localhost:5011/predict/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="ecg.jpg"
Content-Type: image/jpg

< ./ecg.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET http://localhost:5011/